package com.blackbox.domain.model.timeline

/**
 * Pre-computed aggregation of a single day's collected data.
 *
 * Generated by the [DailySummaryWorker] at end-of-day and provides
 * fast access to common queries without scanning raw records.
 * Includes a hash chain for data integrity verification.
 *
 * @property id Database primary key (0 for unsaved summaries).
 * @property date ISO date string (e.g., "2026-02-14").
 * @property totalSteps Step counter total for the day.
 * @property totalDistanceMeters Total distance traveled derived from location points.
 * @property timeAtHomeMinutes Minutes spent at the "Home" known place.
 * @property timeAtWorkMinutes Minutes spent at the "Work" known place.
 * @property timeInTransitMinutes Minutes spent in transit.
 * @property screenOnCount Number of times the screen was turned on.
 * @property totalScreenTimeMinutes Total minutes the screen was on.
 * @property mostUsedApps Top apps ranked by usage time.
 * @property locationsVisited Places visited with durations.
 * @property activityBreakdown Minutes per activity type (e.g., "STILL" to 480).
 * @property noiseAvgDb Average ambient noise level for the day.
 * @property firstScreenOn Timestamp of first screen unlock (epoch ms).
 * @property lastScreenOff Timestamp of last screen off before sleep (epoch ms).
 * @property sleepStartEstimate Estimated sleep start (epoch ms).
 * @property sleepEndEstimate Estimated sleep end (epoch ms).
 * @property dayHash SHA-256 hash of all raw records for integrity chain.
 * @property previousDayHash Hash of the previous day's summary for chain verification.
 * @property summaryText AI-generated natural language summary of the day.
 * @property createdAt When this summary was generated (epoch ms).
 * @property updatedAt When this summary was last updated (epoch ms).
 */
data class DailySummary(
    val id: Long = 0,
    val date: String,
    val totalSteps: Int = 0,
    val totalDistanceMeters: Double = 0.0,
    val timeAtHomeMinutes: Int = 0,
    val timeAtWorkMinutes: Int = 0,
    val timeInTransitMinutes: Int = 0,
    val screenOnCount: Int = 0,
    val totalScreenTimeMinutes: Int = 0,
    val mostUsedApps: List<AppUsageSummary> = emptyList(),
    val locationsVisited: List<VisitedLocation> = emptyList(),
    val activityBreakdown: Map<String, Int> = emptyMap(),
    val noiseAvgDb: Double? = null,
    val firstScreenOn: Long? = null,
    val lastScreenOff: Long? = null,
    val sleepStartEstimate: Long? = null,
    val sleepEndEstimate: Long? = null,
    val dayHash: String? = null,
    val previousDayHash: String? = null,
    val summaryText: String? = null,
    val createdAt: Long = 0,
    val updatedAt: Long = 0,
)

/**
 * Summary of a single app's usage for a day.
 *
 * @property packageName Android package name.
 * @property displayName Human-readable app name.
 * @property usageMinutes Total foreground usage in minutes.
 */
data class AppUsageSummary(
    val packageName: String,
    val displayName: String,
    val usageMinutes: Int,
)

/**
 * A location visited during a day with duration and timestamps.
 *
 * @property placeId Reference to a [KnownPlace], if matched.
 * @property name Display name of the location.
 * @property latitude Center latitude of the visited location.
 * @property longitude Center longitude of the visited location.
 * @property durationMinutes Total time spent at this location.
 * @property arrivedAt Arrival timestamp (epoch ms).
 * @property departedAt Departure timestamp (epoch ms).
 */
data class VisitedLocation(
    val placeId: Long? = null,
    val name: String,
    val latitude: Double,
    val longitude: Double,
    val durationMinutes: Int,
    val arrivedAt: Long,
    val departedAt: Long,
)
